{
    "name": "Incipient Contact Customization",
    "version": "19.0.1.0.0",
    "description": """ This module is Contact Customization""",
    "author": "Incipientcorp",
    "maintainer": "Incipientcorp",
    "depends": ['base', 'contacts', 'account', 'sale'],
    "website": "www.incipientcorp.com",
    "summary": "Odoo 19 Contact Customization.",
    "license": "AGPL-3",
    "category": "apps",
    'data': [
        'data/ir_sequence_data.xml',
        'security/ir.model.access.csv',
        'views/res_partner.xml',
        'views/customer_division.xml',
        'views/discretionary_price_views.xml',
        'views/vendor_contract_views.xml',
        'views/sale_order_views.xml',
        'views/customer_contract.xml',
        'wizard/contract_import_wizard_views.xml',
        'wizard/extraction_report_wizard_views.xml',
        'report/distraction_report_views.xml',
        'report/extraction_report_views.xml',
        'views/menu_views.xml',
    ],
}
