{
    'name': 'Sale Credit Hold',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'Put sale orders on credit hold when customer exceeds credit limit',
    'author': 'Incipient Corp',
    'website': 'www.incipientcorp.com',
    'license': 'OPL-1',
    'depends': [
        'sale',
        'sale_management',
        'account',
        'stock',
        'mail',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template.xml',
        'wizard/wizard_credit_release_view.xml',
        'views/res_partner.xml',
        'views/sale_order_view.xml',
    ],
    'installable': True,
    'application': False,
    'images': ['static/description/banner.gif'],
    'price': 40,
    'currency': 'USD',
}